# Generated by Django 4.1 on 2022-09-19 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_client_client_id_alter_tokens_client_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokens",
            name="access_token",
            field=models.CharField(default="empty", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tokens",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tokens",
            name="updated",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
