# Generated by Django 4.1 on 2022-08-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScannedPackages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipment_id", models.CharField(max_length=50)),
                ("client_id", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "scanned package",
                "verbose_name_plural": "scanned packages",
            },
        ),
    ]
