# Generated by Django 4.1 on 2022-08-31 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("querier", "0002_alter_scannedpackages_client_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scannedpackages",
            name="client_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="authentication.client"
            ),
        ),
    ]
