# Generated by Django 4.1 on 2022-09-03 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_client_client_id_alter_tokens_client_id"),
        ("querier", "0003_alter_scannedpackages_client_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scannedpackages",
            name="client_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="authentication.client",
                to_field="client_id",
            ),
        ),
    ]
