# Generated by Django 4.1 on 2022-09-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("querier", "0004_alter_scannedpackages_client_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="scannedpackages",
            name="receiver_address",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="scannedpackages",
            name="receiver_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="scannedpackages",
            name="receiver_phone",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
