# Generated by Django 4.1 on 2022-09-20 05:07

from django.db import migrations, models
import django.db.models.deletion
import main.app


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_tokens_access_token_tokens_created_tokens_updated"),
        ("querier", "0005_scannedpackages_receiver_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientQuerier",
            fields=[
                (
                    "client_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentication.client",
                    ),
                ),
            ],
            bases=("authentication.client", main.app.app),
        ),
    ]
