# Generated by Django 4.1 on 2022-10-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querier', '0006_clientquerier'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedScannedPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('receiver_name', models.CharField(max_length=50, null=True)),
                ('receiver_phone', models.CharField(max_length=50, null=True)),
                ('receiver_address', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'failed scanned package',
                'verbose_name_plural': 'failed scanned packages',
            },
        ),
    ]
