# Generated by Django 4.1 on 2022-10-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querier', '0007_failedscannedpackages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='failedscannedpackages',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='failedscannedpackages',
            old_name='shipment',
            new_name='shipment_id',
        ),
    ]
