# Generated by Django 4.1 on 2022-10-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querier', '0008_rename_client_failedscannedpackages_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedpackages',
            name='shipment_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
