# Generated by Django 4.1 on 2022-10-16 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('querier', '0009_alter_scannedpackages_shipment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedscannedpackages',
            name='user_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scannedpackages',
            name='user_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
